package com.cs203.tariffg4t2.model.chatbot;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Knowledge base entity for chatbot RAG (Retrieval Augmented Generation)
 * Stores content with vector embeddings for semantic search
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "chatbot_knowledge")
public class ChatbotKnowledge {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * The actual knowledge content (text that will be retrieved)
     */
    @Column(name = "content", nullable = false, columnDefinition = "TEXT")
    private String content;
    
    /**
     * Category for filtering: "hs_code", "tariff_guide", "faq", "general"
     */
    @Column(name = "category", length = 100)
    private String category;
    
    /**
     * Subcategory for more granular filtering
     */
    @Column(name = "subcategory", length = 100)
    private String subcategory;
    
    /**
     * Additional metadata stored as JSON (e.g., source, tags, references)
     */
    @Column(name = "metadata", columnDefinition = "JSONB")
    private String metadata;
    
    /**
     * Vector embedding for semantic similarity search (1536 dimensions)
     * Generated by OpenAI's text-embedding-3-small model
     */
    @Column(name = "embedding", columnDefinition = "vector(1536)")
    private String embedding;
    
    @Column(name = "created_at")
    private LocalDateTime createdAt;
    
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
    
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
    
    /**
     * Constructor for creating knowledge entries without embedding
     * Embedding will be generated later
     */
    public ChatbotKnowledge(String content, String category, String subcategory) {
        this.content = content;
        this.category = category;
        this.subcategory = subcategory;
    }
    
    /**
     * Constructor with metadata
     */
    public ChatbotKnowledge(String content, String category, String subcategory, String metadata) {
        this.content = content;
        this.category = category;
        this.subcategory = subcategory;
        this.metadata = metadata;
    }
}
